language: java

#Cache the directories for STARTS artifacts and Maven downloads
cache:
  directories:
    - $HOME/build/ksong/java-design-patterns/abstract-document/.starts/
    - $HOME/build/ksong/java-design-patterns/abstract-document/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/abstract-factory/.starts/
    - $HOME/build/ksong/java-design-patterns/abstract-factory/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/adapter/.starts/
    - $HOME/build/ksong/java-design-patterns/adapter/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/aggregator-microservices/aggregator-service/.starts/
    - $HOME/build/ksong/java-design-patterns/aggregator-microservices/aggregator-service/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/aggregator-microservices/information-microservice/.starts/
    - $HOME/build/ksong/java-design-patterns/aggregator-microservices/information-microservice/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/aggregator-microservices/inventory-microservice/.starts/
    - $HOME/build/ksong/java-design-patterns/aggregator-microservices/inventory-microservice/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/api-gateway/api-gateway-service/.starts/
    - $HOME/build/ksong/java-design-patterns/api-gateway/api-gateway-service/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/api-gateway/image-microservice/.starts/
    - $HOME/build/ksong/java-design-patterns/api-gateway/image-microservice/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/api-gateway/price-microservice/.starts/
    - $HOME/build/ksong/java-design-patterns/api-gateway/price-microservice/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/async-method-invocation/.starts/
    - $HOME/build/ksong/java-design-patterns/async-method-invocation/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/balking/.starts/
    - $HOME/build/ksong/java-design-patterns/balking/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/bridge/.starts/
    - $HOME/build/ksong/java-design-patterns/bridge/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/builder/.starts/
    - $HOME/build/ksong/java-design-patterns/builder/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/business-delegate/.starts/
    - $HOME/build/ksong/java-design-patterns/business-delegate/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/caching/.starts/
    - $HOME/build/ksong/java-design-patterns/caching/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/callback/.starts/
    - $HOME/build/ksong/java-design-patterns/callback/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/chain/.starts/
    - $HOME/build/ksong/java-design-patterns/chain/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/command/.starts/
    - $HOME/build/ksong/java-design-patterns/command/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/composite/.starts/
    - $HOME/build/ksong/java-design-patterns/composite/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/converter/.starts/
    - $HOME/build/ksong/java-design-patterns/converter/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/cqrs/.starts/
    - $HOME/build/ksong/java-design-patterns/cqrs/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/dao/.starts/
    - $HOME/build/ksong/java-design-patterns/dao/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/data-bus/.starts/
    - $HOME/build/ksong/java-design-patterns/data-bus/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/data-mapper/.starts/
    - $HOME/build/ksong/java-design-patterns/data-mapper/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/data-transfer-object/.starts/
    - $HOME/build/ksong/java-design-patterns/data-transfer-object/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/decorator/.starts/
    - $HOME/build/ksong/java-design-patterns/decorator/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/delegation/.starts/
    - $HOME/build/ksong/java-design-patterns/delegation/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/dependency-injection/.starts/
    - $HOME/build/ksong/java-design-patterns/dependency-injection/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/double-checked-locking/.starts/
    - $HOME/build/ksong/java-design-patterns/double-checked-locking/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/double-dispatch/.starts/
    - $HOME/build/ksong/java-design-patterns/double-dispatch/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/event-aggregator/.starts/
    - $HOME/build/ksong/java-design-patterns/event-aggregator/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/event-asynchronous/.starts/
    - $HOME/build/ksong/java-design-patterns/event-asynchronous/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/event-driven-architecture/.starts/
    - $HOME/build/ksong/java-design-patterns/event-driven-architecture/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/event-queue/.starts/
    - $HOME/build/ksong/java-design-patterns/event-queue/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/event-sourcing/.starts/
    - $HOME/build/ksong/java-design-patterns/event-sourcing/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/execute-around/.starts/
    - $HOME/build/ksong/java-design-patterns/execute-around/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/extension-objects/.starts/
    - $HOME/build/ksong/java-design-patterns/extension-objects/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/facade/.starts/
    - $HOME/build/ksong/java-design-patterns/facade/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/factory-kit/.starts/
    - $HOME/build/ksong/java-design-patterns/factory-kit/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/factory-method/.starts/
    - $HOME/build/ksong/java-design-patterns/factory-method/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/feature-toggle/.starts/
    - $HOME/build/ksong/java-design-patterns/feature-toggle/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/fluentinterface/.starts/
    - $HOME/build/ksong/java-design-patterns/fluentinterface/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/flux/.starts/
    - $HOME/build/ksong/java-design-patterns/flux/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/flyweight/.starts/
    - $HOME/build/ksong/java-design-patterns/flyweight/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/front-controller/.starts/
    - $HOME/build/ksong/java-design-patterns/front-controller/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/guarded-suspension/.starts/
    - $HOME/build/ksong/java-design-patterns/guarded-suspension/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/half-sync-half-async/.starts/
    - $HOME/build/ksong/java-design-patterns/half-sync-half-async/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/hexagonal/.starts/
    - $HOME/build/ksong/java-design-patterns/hexagonal/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/intercepting-filter/.starts/
    - $HOME/build/ksong/java-design-patterns/intercepting-filter/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/interpreter/.starts/
    - $HOME/build/ksong/java-design-patterns/interpreter/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/iterator/.starts/
    - $HOME/build/ksong/java-design-patterns/iterator/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/layers/.starts/
    - $HOME/build/ksong/java-design-patterns/layers/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/lazy-loading/.starts/
    - $HOME/build/ksong/java-design-patterns/lazy-loading/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/marker/.starts/
    - $HOME/build/ksong/java-design-patterns/marker/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/mediator/.starts/
    - $HOME/build/ksong/java-design-patterns/mediator/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/memento/.starts/
    - $HOME/build/ksong/java-design-patterns/memento/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/message-channel/.starts/
    - $HOME/build/ksong/java-design-patterns/message-channel/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/model-view-controller/.starts/
    - $HOME/build/ksong/java-design-patterns/model-view-controller/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/model-view-presenter/.starts/
    - $HOME/build/ksong/java-design-patterns/model-view-presenter/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/module/.starts/
    - $HOME/build/ksong/java-design-patterns/module/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/monad/.starts/
    - $HOME/build/ksong/java-design-patterns/monad/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/monostate/.starts/
    - $HOME/build/ksong/java-design-patterns/monostate/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/multiton/.starts/
    - $HOME/build/ksong/java-design-patterns/multiton/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/mute-idiom/.starts/
    - $HOME/build/ksong/java-design-patterns/mute-idiom/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/mutex/.starts/
    - $HOME/build/ksong/java-design-patterns/mutex/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/naked-objects/dom/.starts/
    - $HOME/build/ksong/java-design-patterns/naked-objects/dom/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/naked-objects/integtests/.starts/
    - $HOME/build/ksong/java-design-patterns/naked-objects/integtests/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/null-object/.starts/
    - $HOME/build/ksong/java-design-patterns/null-object/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/object-mother/.starts/
    - $HOME/build/ksong/java-design-patterns/object-mother/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/object-pool/.starts/
    - $HOME/build/ksong/java-design-patterns/object-pool/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/page-object/.starts/
    - $HOME/build/ksong/java-design-patterns/page-object/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/partial-response/.starts/
    - $HOME/build/ksong/java-design-patterns/partial-response/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/poison-pill/.starts/
    - $HOME/build/ksong/java-design-patterns/poison-pill/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/private-class-data/.starts/
    - $HOME/build/ksong/java-design-patterns/private-class-data/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/producer-consumer/.starts/
    - $HOME/build/ksong/java-design-patterns/producer-consumer/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/promise/.starts/
    - $HOME/build/ksong/java-design-patterns/promise/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/property/.starts/
    - $HOME/build/ksong/java-design-patterns/property/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/prototype/.starts/
    - $HOME/build/ksong/java-design-patterns/prototype/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/proxy/.starts/
    - $HOME/build/ksong/java-design-patterns/proxy/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/publish-subscribe/.starts/
    - $HOME/build/ksong/java-design-patterns/publish-subscribe/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/queue-load-leveling/.starts/
    - $HOME/build/ksong/java-design-patterns/queue-load-leveling/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/reactor/.starts/
    - $HOME/build/ksong/java-design-patterns/reactor/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/reader-writer-lock/.starts/
    - $HOME/build/ksong/java-design-patterns/reader-writer-lock/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/repository/.starts/
    - $HOME/build/ksong/java-design-patterns/repository/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/resource-acquisition-is-initialization/.starts/
    - $HOME/build/ksong/java-design-patterns/resource-acquisition-is-initialization/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/semaphore/.starts/
    - $HOME/build/ksong/java-design-patterns/semaphore/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/servant/.starts/
    - $HOME/build/ksong/java-design-patterns/servant/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/service-layer/.starts/
    - $HOME/build/ksong/java-design-patterns/service-layer/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/service-locator/.starts/
    - $HOME/build/ksong/java-design-patterns/service-locator/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/singleton/.starts/
    - $HOME/build/ksong/java-design-patterns/singleton/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/specification/.starts/
    - $HOME/build/ksong/java-design-patterns/specification/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/state/.starts/
    - $HOME/build/ksong/java-design-patterns/state/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/step-builder/.starts/
    - $HOME/build/ksong/java-design-patterns/step-builder/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/strategy/.starts/
    - $HOME/build/ksong/java-design-patterns/strategy/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/template-method/.starts/
    - $HOME/build/ksong/java-design-patterns/template-method/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/thread-pool/.starts/
    - $HOME/build/ksong/java-design-patterns/thread-pool/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/throttling/.starts/
    - $HOME/build/ksong/java-design-patterns/throttling/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/tls/.starts/
    - $HOME/build/ksong/java-design-patterns/tls/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/tolerant-reader/.starts/
    - $HOME/build/ksong/java-design-patterns/tolerant-reader/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/twin/.starts/
    - $HOME/build/ksong/java-design-patterns/twin/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/value-object/.starts/
    - $HOME/build/ksong/java-design-patterns/value-object/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/visitor/.starts/
    - $HOME/build/ksong/java-design-patterns/visitor/jdeps-cache/
    - $HOME/build/ksong/java-design-patterns/observer/.starts
    - $HOME/build/ksong/java-design-patterns/observer/jdeps-cache
#    - $HOME/.m2
jdk:
- oraclejdk8

env:
  global:
  - GH_REF: github.com/iluwatar/java-design-patterns.git
  - secure: LxTDuNS/rBWIvKkaEqr79ImZAe48mCdoYCF41coxNXgNoippo4GIBArknqtv+XvdkiuRZ1yGyj6pn8GU33c/yn+krddTUkVCwTbVatbalW5jhQjDbHYym/JcxaK9ZS/3JTeGcWrBgiPqHEEDhCf26vPZsXoMSeVCEORVKTp1BSg=
  - secure: "eoWlW9GyTJY04P8K3pxayXwU9/hmptQg/LfirispQkV9YvmziCfSzXnatnBhNfud98sCzY8BScXnb+OWLTnjLKpId4rtEqb0aJ40Jc32cUKzgzFAUn7cNcDAbUIfyPAGVqyQqfj/11wYSADwWMMOPlW97ExUtoyiH2WenXuRHso="
  
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# default install command is just "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e

script:
- mvn starts:starts

after_success:
- bash update-ghpages.sh


# use latest java version available instead of travis default
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    - kaisong2@illinois.edu
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3319623945358a093a6f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

sudo: required